version: '3'

dotenv: ['.env', '.env.test']

vars:
  LOCAL_SERVICES: "movie kafka schema-registry"
  BUILD_CMD: "docker-compose build --no-cache"
  RUN_CMD: "docker-compose up -d {{.LOCAL_SERVICES}}"
  STOP_CMD: "docker-compose down -v"
  BASH_MOVIE_CMD: "docker exec -it movie-app sh"
  LOGS_CMD: "docker-compose logs -f --tail=500"
  LOGS_MOVIE_CMD: "docker-compose logs -f --tail=500 movie-app"

tasks:
  run:
    desc: Execute local project
    cmds:
      - task: build
      - '{{.RUN_CMD}}'
  build:
    desc: Build container
    cmds:
      - '{{.BUILD_CMD}}'
  stop:
    desc: Stop env
    cmds:
      - '{{.STOP_CMD}}'
  movie:
    desc: Enter movie bash
    cmds:
      - '{{.BASH_MOVIE_CMD}}'
  logs:
    desc: Docker logs
    cmds:
      - '{{.LOGS_CMD}}'
  logs:movie:
    desc: Docker movie logs
    cmds:
      - '{{.LOGS_MOVIE_CMD}}'
