version: '3'

dotenv: ['.env', '.env.test']

vars:
  LOCAL_SERVICES: "kafka zookeeper"
  BUILD_CMD: "docker-compose build --no-cache"
  RUN_CMD: "docker-compose up -d {{.LOCAL_SERVICES}}"
  STOP_CMD: "docker-compose down -v"
  LOGS_CMD: "docker-compose logs -f --tail=500"

tasks:
  run:
    desc: Execute local project
    cmds:
      - task: build
      - '{{.RUN_CMD}}'
  build:
    desc: Build container
    cmds:
      - '{{.BUILD_CMD}}'
  stop:
    desc: Stop env
    cmds:
      - '{{.STOP_CMD}}'
  logs:
    desc: Docker logs
    cmds:
      - '{{.LOGS_CMD}}'
