version: '3'

dotenv: ['.env', '.env.test']

vars:
  LOCAL_SERVICES: "app kafka schema-registry"
  BUILD_CMD: "docker-compose build --no-cache"
  RUN_CMD: "docker-compose up -d {{.LOCAL_SERVICES}}"
  STOP_CMD: "docker-compose down -v"
  BASH_CMD: "docker exec -it book-app sh"
  LOGS_CMD: "docker-compose logs -f --tail=500"
  LOGS_APP_CMD: "docker-compose logs -f --tail=500 app"

tasks:
  run:
    desc: Execute local project
    cmds:
      - task: build
      - '{{.RUN_CMD}}'
  build:
    desc: Build container
    cmds:
      - '{{.BUILD_CMD}}'
  stop:
    desc: Stop env
    cmds:
      - '{{.STOP_CMD}}'
  app:
    desc: Enter app bash
    cmds:
      - '{{.BASH_CMD}}'
  logs:
    desc: Docker logs
    cmds:
      - '{{.LOGS_CMD}}'
  logs:app:
    desc: Docker app logs
    cmds:
      - '{{.LOGS_APP_CMD}}'
